# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import dog_pb2 as dog__pb2


class DogStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.GetMyDog = channel.unary_unary(
        '/Dog/GetMyDog',
        request_serializer=dog__pb2.GetMyDogMessage.SerializeToString,
        response_deserializer=dog__pb2.MyDogResponse.FromString,
        )


class DogServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def GetMyDog(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_DogServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'GetMyDog': grpc.unary_unary_rpc_method_handler(
          servicer.GetMyDog,
          request_deserializer=dog__pb2.GetMyDogMessage.FromString,
          response_serializer=dog__pb2.MyDogResponse.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'Dog', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
