version: '3.7'
services:
  proxy:
    build:
      context: ./proxy
      dockerfile: Dockerfile
    ports:
      - '8000:8000'

  grpc-server:
    build:
      context: ./server
      dockerfile: Dockerfile
